apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nok-lb-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.100-172.18.0.120 # kpt-set: ${metallb-pool-range}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: production-advertisement-2
  namespace: metallb-system
spec:
  ipAddressPools:
  - nok-lb-pool
