apiVersion: v1
kind: ConfigMap
metadata:
  name: bbm-grafana-datasources-config
  namespace: nok-bbm
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: DS_PROMETHEUS
        access: proxy
        url: http://bbm-prometheus-svc:9090
        jsonData:
          httpMethod: POST
          timeout: 60
          manageAlerts: false
          prometheusType: Prometheus
          cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
