 
---  
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-sub-mgmt-subscribers-on-change
  labels:
    type: bng
spec:
  paths:
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv4/ip-address/address"
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv6/dhcp6-lease/client-address"
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv6/pd/ip-prefix/prefix"
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv6/slaac/address"
    - "/state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=*]/oper-state"
    - "/state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=*]/master-since"
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-sub-mgmt-subscribers-sample
  labels:
    type: bng
spec:
  paths:
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv4/ip-address/address"
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv6/dhcp6-lease/client-address"
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv6/pd/ip-prefix/prefix"
    - "/state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[id=*][type=ppp]/ipv6/slaac/address"
    - "/state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=*]/oper-state"
    - "/state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=*]/master-since"
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s    
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Processor
metadata:
  namespace: nok-bng
  name: source-domain-removal
spec:
  type: event-strings
  config:
    tage-names:
      - "source"
    transforms:
      - trim-suffix:
          apply-on: "value"
          suffix: ".service.consul"           
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Output
metadata:
  namespace: nok-bng
  name: op-fluent
  labels:
    type: bng-state
spec:
  type: tcp
  config:
    address: "tel-fb:6000"
    format: json  
    rate: 10ms 
    keep-alive: 30s
    retry-interval: 30s
    enable-metrics: false 
    delimiter: "\n"    
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Output
metadata:
  namespace: nok-bng
  name: op-state
  labels:
    type: bng-state
spec:
  type: file
  config:
    file-type: stdout
    format: event
  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-bng
  name: bng-state
spec:
  clusterRef: bng-state
  enabled: true
  # Select targets by label
  targetSelectors:
    - matchLabels:
        vendor: Nokia
        role: bng
  # Select subscriptions by label
  subscriptionRefs:
    - sros-sub-mgmt-subscribers-on-change
    - sros-sub-mgmt-subscribers-sample
  # Select outputs by label
  outputs:
    outputSelectors:
      - matchLabels:
          type: bng-state  
    processorRefs:
      - oper-state-to-int  
      - source-domain-removal  
            
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Cluster
metadata:
  namespace: nok-bng
  name: bng-state
spec:
  replicas: 1
  image: ghcr.io/openconfig/gnmic:latest          