# Source: clabernetes/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clabernetes-service-account
  namespace: nok-base
  labels:
    chart: clabernetes-0.3.3
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: clabernetes-service-account
    clabernetes/component: service-account
