apiVersion: v1
kind: Service
metadata:
  name: bbm-prometheus-svc
  namespace: nok-bbm
  labels:
    app: bbm-prometheus
spec:
  selector:
    app: bbm-prometheus
  type: ClusterIP # Or ClusterIP if you prefer internal access
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
