apiVersion: v1
kind: ConfigMap
metadata:
  name: nokia-srsim-sros-bngt
  labels:
    app: bbm-prometheus
  namespace: nok-bbm
data:
  nokia_srsim-sros_bngt.json: |
    [
      {
        "targets": [
          "172.21.20.21"
        ],
        "labels": {
          "hostname": "clab-sros_bngt-agg",
          "kind": "nokia_srsim"
        }
      },
      {
        "targets": [
          "172.21.20.11"
        ],
        "labels": {
          "hostname": "clab-sros_bngt-bng1",
          "kind": "nokia_srsim"
        }
      },
      {
        "targets": [
          "172.21.20.12"
        ],
        "labels": {
          "hostname": "clab-sros_bngt-bng2",
          "kind": "nokia_srsim"
        }
      },
      {
        "targets": [
          "172.21.20.22"
        ],
        "labels": {
          "hostname": "clab-sros_bngt-core",
          "kind": "nokia_srsim"
        }
      }
    ]
