apiVersion: v1
kind: Service
metadata:
  name: prom-bbm-http
  namespace: monitoring
  annotations:
    netopskube.io/bbm: "true"
    netopskube.io/prober: "http"
    netopskube.io/scheme: "http"
    netopskube.io/path: "/-/ready"
spec:
  type: ClusterIP
  selector:
    # Prometheus pods created by the operator -> app.kubernetes.io/name: prometheus 
    app.kubernetes.io/name: prometheus         # example: label often equals Prometheus CR name
  ports:
    - name: web
      port: 9090
      targetPort: web
      protocol: TCP