apiVersion: v1
kind: Secret
metadata:
  namespace: nok-bng
  name: device-credentials
  namespace: nok-bng
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: NokiaSros1!
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetProfile
metadata:
  namespace: nok-bng
  name: default-profile
  namespace: nok-bng  
spec:
  # Reference to a Secret containing username/password
  credentialsRef: device-credentials
  # TLS without server certificate verification
  #tls: {}
  # Connection timeout
  timeout: 10s
---  
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  namespace: nok-bng
  name: clab-sros-bngt-agg
  labels:
    vendor: Nokia
    role: bng-ext
spec:
  address: clab-sros-bngt-agg.service.consul:57400
  profile: default-profile
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  namespace: nok-bng
  name: clab-sros-bngt-core
  labels:
    vendor: Nokia
    role: bng-ext
spec:
  address: clab-sros-bngt-core.service.consul:57400
  profile: default-profile  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  namespace: nok-bng
  name: clab-sros-bngt-bng1
  labels:
    vendor: Nokia
    role: bng
spec:
  address: clab-sros-bngt-bng1.service.consul:57400
  profile: default-profile   
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  namespace: nok-bng
  name: clab-sros-bngt-bng2
  labels:
    vendor: Nokia
    role: bng
spec:
  address: clab-sros-bngt-bng2.service.consul:57400
  profile: default-profile    
---  
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-router-interfaces
  labels:
    type: bng
spec:
  paths:
    - /state/router[router-name=*]/interface[interface-name=*]/statistics/ip/in-octets
    - /state/router[router-name=*]/interface[interface-name=*]/statistics/ip/out-octets
    - /state/router[router-name=*]/interface[interface-name=*]/statistics/mpls/in-octets
    - /state/router[router-name=*]/interface[interface-name=*]/statistics/mpls/out-octets
    - /state/port[port-id=*]/ethernet/statistics/in-octets
    - /state/port[port-id=*]/ethernet/statistics/out-octets
    - /state/port[port-id=*]/ethernet/statistics/in-utilization
    - /state/port[port-id=*]/ethernet/statistics/out-utilization
    - /state/port[port-id=*]/oper-state
    - /state/port[port-id=*]/ethernet/statistics/in-errors
    - /state/port[port-id=*]/ethernet/statistics/out-errors
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-system-performance
  labels:
    type: bng
spec:
  paths:
    - /state/system/cpu[sample-period=60]/summary/usage
    - /state/system/memory-pools/summary/available-memory
    - /state/system/memory-pools/summary/current-total-size
    - /state/system/memory-pools/summary/total-in-use
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-sub-mgmt-statistics
  labels:
    type: bng
spec:
  paths:
    - /state/subscriber-mgmt/statistics/sessions[counter=ppp-sessions-total-established]/current-value
    - /state/subscriber-mgmt/statistics/total-hosts[counter=ipv4]
    - /state/subscriber-mgmt/statistics/total-hosts[counter=ipv6]
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s   
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-fp-sub-mgmt-resources
  labels:
    type: bng
spec:
  paths:
    - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/egress-queues
    - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/ingress-queues
    - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/ingress-policers
    - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/egress-policers
    - /state/card[slot-number=1]/mda[mda-slot=1]/resource-usage/sap-instances
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-sub-mgmt-subscribers
  labels:
    type: bng
spec:
  paths:
    - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/up-time
    - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/ipv4/forwarding-state
    - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/ipv6/pd/forwarding-state
    - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/ipv6/slaac/forwarding-state
    - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/ingress/qos/statistics/out-profile-forwarded-octets
    - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/egress/qos/statistics/out-exceed-profile-forwarded-octets
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s   
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-system-resources
  labels:
    type: bng
spec:
  paths:
    - /state/system/resource-usage/subscriber-next-hop-entries
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s   
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-bng
  name: sros-sub-mgmt-redundancy
  labels:
    type: bng
spec:
  paths:
    - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/advertisement-interval-errors
    - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/advertisement-interval-discards
    - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/master-changes
    - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/become-master
    - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/become-non-master
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s     
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Processor
metadata:
  namespace: nok-bng
  name: oper-state-to-int
spec:
  type: event-strings
  config:
    value-names:
      - ".*"
    transforms:
      - replace:
          apply-on: "value"
          old: "up"
          new: "1" 
      - replace:
          apply-on: "value"
          old: "down"
          new: "0"           
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Output
metadata:
  namespace: nok-bng
  name: file-event-output
  labels:
    type: bng-ext-output
spec:
  type: file
  config:
    file-type: stdout  # or file path
    format: event  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Output
metadata:
  namespace: nok-bng
  name: prom-output
  labels:
    type: bng-ext-output
spec:
  type: prometheus
  # config:
  #   listen: ":9804"
  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-bng
  name: bng-ext-tel
spec:
  clusterRef: bng-metrics
  enabled: true
  # Select targets by label
  targetSelectors:
    - matchLabels:
        vendor: Nokia
        role: bng-ext
  # Select subscriptions by label
  subscriptionRefs:
    - sros-router-interfaces
    - sros-system-performance
  # Select outputs by label
  outputs:
    outputSelectors:
      - matchLabels:
          type: bng-ext-output  
    processorRefs:
      - oper-state-to-int    
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-bng
  name: bng-tel
spec:
  clusterRef: bng-metrics
  enabled: true
  # Select targets by label
  targetSelectors:
    - matchLabels:
        vendor: Nokia
        role: bng
  subscriptionSelectors:
    - matchLabels:
        type: bng
  outputs:
    outputSelectors:
      - matchLabels:
          type: bng-ext-output  
    processorRefs:
      - oper-state-to-int              
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Cluster
metadata:
  namespace: nok-bng
  name: bng-metrics
spec:
  replicas: 1
  image: ghcr.io/openconfig/gnmic:latest          