apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nok-gitea-ingress
  namespace: nok-git
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1 # Rewrites the URL path for the backend service
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  # TODO: activate later on, after core-dns-updater capabilities get extended to handle multiple host entries.
  # annotations:
  #   netopskube.io/bbm: "true"
  #   netopskube.io/prober: http
  #   netopskube.io/scheme: http
spec:
  ingressClassName: nginx
  rules:
  - host: gitea.nok.local # kpt-set: ${ingress-host}
    http:
      paths:
      #      - path: /prometheus(/|$)(.*)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea-http
            port:
              number: 3000
