apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nok-apps-portal-ingress # Give it a distinct name
  namespace: nok-bng
spec:
  ingressClassName: nginx
  rules:
  - host: bng.nok.local
    http:
      paths:
      - path: /
        pathType: Prefix # Use Prefix for exact match or prefix matching without regex
        backend:
          service:
            name: nok-apps-portal-service
            port:
              number: 80