apiVersion: v1
kind: ConfigMap
metadata:
  name: nok-apps-menu-config
  namespace: nok-bng
data:
  menu-config.json: |
    [
      {"name": "Prometheus", "path": "/prometheus/graph", "openInNewTab": false},
      {"name": "Grafana", "path": "/grafana", "openInNewTab": true},
      {"name": "GNMIC", "path": "/gnmic/metrics", "openInNewTab": false},
      {"name": "Alertmanager", "path": "/alertmanager", "openInNewTab": false},
      {"name": "Smokeping", "path": "/smokeping/metrics", "openInNewTab": false}
    ]