apiVersion: v1
kind: ConfigMap
metadata:
  name: nok-apps-menu-config
  namespace: nok-dia
data:
  menu-config.json: |
    [
      {"name": "Prometheus", "path": "/prometheus/graph", "openInNewTab": false},
      {"name": "Grafana", "path": "/grafana/dashboards", "openInNewTab": false},
      {"name": "Alertmanager", "path": "/alertmanager", "openInNewTab": false},
      {"name": "Gitea", "path": "/gitea/nok/nok-dia-resources", "openInNewTab": false},
      {"name": "BBM (Self Monitoring)", "path": "/bbm/dashboards", "openInNewTab": false}
    ]
