apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deploy
  labels:
    app: consul
  namespace: nok-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - args:
        - agent
        - -server
        - -ui
        - -node=server-1
        - -bootstrap-expect=1
        - -client=0.0.0.0
        image: hashicorp/consul
        imagePullPolicy: IfNotPresent
        name: consul
        ports:
        - containerPort: 8500
          name: consul-http
          protocol: TCP
        - containerPort: 8600 # Added for Consul DNS (UDP)
          name: consul-dns-udp
          protocol: UDP
        - containerPort: 8600 # Added for Consul DNS (TCP)
          name: consul-dns-tcp
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: consul-svc
  namespace: nok-base
spec:
  ports:
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500 # Explicitly map to Consul's HTTP port
  - name: consul-dns-udp # Expose DNS on standard UDP port 53
    port: 8600
    protocol: UDP
    targetPort: 8600 # Map to Consul's internal DNS port 8600
  - name: consul-dns-tcp # Expose DNS on standard TCP port 53
    port: 8600
    protocol: TCP
    targetPort: 8600 # Map to Consul's internal DNS port 8600
  selector:
    app: consul