apiVersion: v1
kind: PersistentVolume
metadata:
  name: nok-apps-portal-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /portal
    type: Directory
