apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nok-apps-portal-pvc
  namespace: nok-base
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: nok-apps-portal-pv
