{
 "title": "Blackbox Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" },
   {
    "name": "NAMESPACE",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blackbox arch version",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "blackbox_exporter_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last config reload",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "blackbox_exporter_config_last_reload_successful",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services HTTP Protocol Check $NAMESPACE",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "probe_success{job=\"nok_services_http\",namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{service}}  /  {{instance}}"
    }
   ]
  },
  {
   "title": "Services TCP Protocol Check $NAMESPACE",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "probe_success{job=\"nok_services_tcp\",namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{service}}  /  {{instance}}"
    }
   ]
  },
  {
   "title": "Ingress Client Side Check $NAMESPACE",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "probe_success{job=\"nok_ingress\",namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{ingress}} / {{instance}}"
    }
   ]
  },
  {
   "title": "SROS SSH Protocol Check",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_success{job=\"ds_file_nokia_srsim_ssh_check\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SROS gNMI Protocol Check",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_success{job=\"ds_file_nokia_srsim_gnmi_check\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Connect for Services",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{service=~\".+\", phase=\"connect\", job=\"nok_services_http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Connect for Ingress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\", job=\"nok_ingress\"}",
     "legendFormat": "{{ingress}} / {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Transfer",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{service=~\".+\", phase=\"transfer\", job=\"nok_services_http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux ICMP RTT Probing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{kind=\"linux\",phase=\"rtt\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux ICMP Probing",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_success{job=\"ds_file_linux_icmp_ping\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } }
 ]
}