{
 "title": "NetOpsKube Status Dashboards",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" },
   {
    "name": "NAMESPACE",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Inventory",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster Resources: Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\"})",
     "legendFormat": "Max Available #"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Allocated #" }
   ]
  },
  {
   "title": "Cluster Resources: CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "CPU Capacity "
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "CPU Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "Available Deployments Heatmap MinimumReplicasAvailable $NAMESPACE",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "kube_deployment_status_condition{namespace=\"$NAMESPACE\",condition=\"Available\",status=\"true\", reason=\"MinimumReplicasAvailable\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Cluster Resources: Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "MEM Capacity "
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "MEM Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "MEM Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "MEM Limits"
    }
   ]
  },
  {
   "title": "Kubernetes Cluster Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" }
   ]
  },
  {
   "title": "Available Deployments Heatmap MinimumReplicasUnavailable $NAMESPACE",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "kube_deployment_status_condition{namespace=\"$NAMESPACE\", condition=\"Available\",status=\"false\", reason=\"MinimumReplicasUnavailable\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment Replicas: Minimum Replicas Unavailable $NAMESPACE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "kube_deployment_status_condition{namespace=\"$NAMESPACE\", reason=\"MinimumReplicasUnavailable\", status='false'}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment Replicas: Status $NAMESPACE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$NAMESPACE\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$NAMESPACE\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$NAMESPACE\"})",
     "legendFormat": "Unavailable "
    },
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=\"$NAMESPACE\"})",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Deployments: Desired vs Current $NAMESPACE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"$NAMESPACE\"} - kube_deployment_status_replicas{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Availability Ratio (available vs spec) $NAMESPACE",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$NAMESPACE\"} / clamp_min(kube_deployment_spec_replicas{namespace=\"$NAMESPACE\"},1)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment: Unavailable Replicas $NAMESPACE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (deployment) (\n  kube_deployment_spec_replicas{namespace=\"$NAMESPACE\"} - kube_deployment_status_replicas_available{namespace=\"$NAMESPACE\"}\n)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "PVC Bound $NAMESPACE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\", namespace=\"$NAMESPACE\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC UN Bound $NAMESPACE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\", namespace=\"$NAMESPACE\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC List $NAMESPACE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$NAMESPACE\"}/1024/1024/1024",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}