apiVersion: v1
kind: ConfigMap
metadata:
  name: srl02-srl1-startup-config
  namespace: nok-test
data:
  startup-config: |-
    set / interface ethernet-1/1 admin-state enable
    set / interface ethernet-1/1 subinterface 0
    set / interface ethernet-1/1 subinterface 0 ipv4
    set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable
    set / interface ethernet-1/1 subinterface 0 ipv4 address 192.168.0.0/31
    set / interface ethernet-1/1 subinterface 0 ipv6
    set / interface ethernet-1/1 subinterface 0 ipv6 admin-state enable
    set / interface ethernet-1/1 subinterface 0 ipv6 address 2002::192.168.0.0/127

    set / network-instance default
    set / network-instance default interface ethernet-1/1.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: srl02-srl2-startup-config
  namespace: nok-test
data:
  startup-config: |-
    set / interface ethernet-1/1 admin-state enable
    set / interface ethernet-1/1 subinterface 0
    set / interface ethernet-1/1 subinterface 0 ipv4
    set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable
    set / interface ethernet-1/1 subinterface 0 ipv4 address 192.168.0.1/31
    set / interface ethernet-1/1 subinterface 0 ipv6
    set / interface ethernet-1/1 subinterface 0 ipv6 admin-state enable
    set / interface ethernet-1/1 subinterface 0 ipv6 address 2002::192.168.0.1/127

    set / network-instance default
    set / network-instance default interface ethernet-1/1.0
---
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: srl02
  namespace: nok-test
spec:
  deployment:
    filesFromConfigMap:
      srl1:
        - filePath: srl1.cfg
          configMapName: srl02-srl1-startup-config
          configMapPath: startup-config
          mode: read
      srl2:
        - filePath: srl2.cfg
          configMapName: srl02-srl2-startup-config
          configMapPath: startup-config
          mode: read
  naming: non-prefixed
  definition:
    containerlab: |-
      # topology documentation: http://containerlab.dev/lab-examples/two-srls/
      name: srl02

      topology:
        nodes:
          srl1:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux
            startup-config: srl1.cfg
          srl2:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux
            startup-config: srl2.cfg

        links:
          - endpoints: ["srl1:e1-1", "srl2:e1-1"]
