# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnmic-config
  namespace: nok-base
data:
  config.yaml: |

    username: admin
    password: NokiaSrl1! 
    skip-verify: true
    encoding: json_ietf
    log: true

    # clustering:
    #   cluster-name: cluster1
    #   targets-watch-timer: 30s
    #   locker:
    #     type: consul
    #     address: consul-svc:8500

    targets:
      srl1:
        subscriptions:
          - sub1

    subscriptions:
      sub1:
        paths:
        - interface[name=ethernet-1/1]/statistics/in-packets
        stream-mode: sample
        sample-interval: 10s
        encoding: ascii

    outputs:
      prom-output:
        type: prometheus

