apiVersion: v1
kind: Service
metadata:
  name: blackbox-svc
  namespace: nok-bbm
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  type: ClusterIP # Or ClusterIP if you prefer internal access
  ports:
    - protocol: TCP
      port: 9115
      targetPort: 9115
