apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: bbm-nok-linux-ping
  namespace: nok-bbm
  labels:
    app: bbm-prometheus
spec:
  jobName: ds_file_linux_icmp_ping
  honorTimestamps: true
  scrapeInterval: 30s
  scrapeTimeout: 7s
  metricsPath: /probe
  scheme: HTTP
  params:
    module:
      - icmp_ping
  httpSDConfigs:
    - url: http://nok-controller.nok-base.svc.cluster.local:8080/targets/blackbox?kind=host
      refreshInterval: 30s
  relabelings:
    - sourceLabels: [__address__]
      separator: ;
      regex: (.*)
      targetLabel: __param_target
      replacement: $1
      action: replace
    - sourceLabels: [hostname]
      separator: ;
      regex: (.*)
      targetLabel: instance
      replacement: $1
      action: replace
    - sourceLabels: [__meta_nht_namespace]
      separator: ;
      regex: (.*)
      targetLabel: namespace
      replacement: $1
      action: replace
    - separator: ;
      regex: (.*)
      targetLabel: __address__
      replacement: blackbox-svc:9115
      action: replace
