apiVersion: v1
kind: Secret
metadata:
  name: device-credentials
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: NokiaSros1!
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetProfile
metadata:
  name: default-profile
spec:
  # Reference to a Secret containing username/password
  credentialsRef: device-credentials
  # TLS without server certificate verification
  #tls: {}
  # Connection timeout
  timeout: 10s
---  
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  name: clab-sros-bngt-agg
  labels:
    vendor: Nokia
    role: bng-ext
spec:
  address: clab-sros-bngt-agg.service.consul:57400
  profile: default-profile
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  name: clab-sros-bngt-core
  labels:
    vendor: Nokia
    role: bng-ext
spec:
  address: clab-sros-bngt-core.service.consul:57400
  profile: default-profile  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  name: clab-sros-bngt-bng1
  labels:
    vendor: Nokia
    role: bng
spec:
  address: clab-sros-bngt-bng1.service.consul:57400
  profile: default-profile   
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  name: clab-sros-bngt-bng2
  labels:
    vendor: Nokia
    role: bng
spec:
  address: clab-sros-bngt-bng2.service.consul:57400
  profile: default-profile    
---  
apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  name: port-state
  labels:
    type: interfaces
spec:
  paths:
    - /state/port[port-id=*]/oper-state
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 10s
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Processor
metadata:
  name: oper-state-to-int
spec:
  type: event-strings
  config:
    value-names:
      - ".*"
    transforms:
      - replace:
          apply-on: "value"
          old: "up"
          new: "1" 
      - replace:
          apply-on: "value"
          old: "down"
          new: "0"           
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Output
metadata:
  name: file-event-output
  labels:
    type: bng-ext-output
spec:
  type: file
  config:
    file-type: stdout  # or file path
    format: event  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Output
metadata:
  name: prom-output
  labels:
    type: bng-ext-output
spec:
  type: prometheus
  config:
    listen: ":9804"
  
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  name: bng-ext-tel
spec:
  clusterRef: bng-metrics
  enabled: true
  # Select targets by label
  targetSelectors:
    - matchLabels:
        vendor: Nokia
        role: bng-ext
  # Select subscriptions by label
  subscriptionSelectors:
    - matchLabels:
        type: interfaces
  # Select outputs by label
  outputs:
    outputSelectors:
      - matchLabels:
          type: bng-ext-output  
    processorRefs:
      - oper-state-to-int          
---
apiVersion: operator.gnmic.dev/v1alpha1
kind: Cluster
metadata:
  name: bng-metrics
spec:
  replicas: 1
  image: ghcr.io/openconfig/gnmic:latest          